---
title: "Resources"
---

## Publications

-   We've made [a library of response diversity related papers](https://www.zotero.org/groups/5297762/response_diversity_network/library) in [Zotero](https://www.zotero.org/). We created the library in November 2023 and will add more papers as we go along.

## Presentations

-   Ross, S.R.P.-J., Petchey, O.L., and the Response Diversity Network (2023) Exploring the biotic drivers of ecological stability through a global collaborative network. *Oral presentation at the annual meeting of the Ecological Society of Japan* ([pdf 13.6MB](assets/presentations/Slides_SR_ESJ_2023.pdf); [pptx 12.3MB](assets/presentations/Slides_SR_ESJ_2023.pptx)).

## Leadership Team and Steering Committee minutes

[Meeting minutes are available in this folder on github.](https://github.com/ResponseDiversityNetwork/RDN-website/tree/main/assets/sc_meeting_mins) This includes minutes from the original Steering Committee, and can also be used for Leadership Team minutes as the network's governance develops.

## Logos

[Various arrangements of the logo are available in this folder on github.](https://github.com/ResponseDiversityNetwork/RDN-website/tree/main/assets/logo)

## Miscellany

-   Notes ([pdf 0.1MB](assets/scoping_chat/scoping_chat_notes.pdf)) and slides ([pdf 4.9MB](assets/scoping_chat/scoping_chat_slides.pdf)) from the scoping meeting held in October 2022.
