---
title: "Who we are"
---

Responsive diversity is a transversal concept and so the network is open to anyone who would like to be part of a community of people interested in any and all things about response diversity. It includes researchers working on many types of systems, problems, and settings, including ecological systems, coupled social-ecological systems, economic-policy-behavioural systems, natural resources, urban landscapes, and nature-people relationships, to name but a few. This diversity is also represented in the many ways in which our research is done, including case studies, theoretical models, large-scale observations, manipulative experiments, and data analyses.

The network is currently composed of over 80 members from more than 50 institutions and 20 countries. Current members include early career researchers (e.g. PhD candidates), researchers later in their careers, and everything in between.


## Steering Committee

A steering committee helps coordinate the development of the network. The committee currently consists of 7 members:

-   [Ceres Barros](https://ceresbarros.wordpress.com/) (University of British Columbia, Canada)
-   [Laura E. Dee](https://www.lauraedee.com/home) (University of Colorado, Boulder, USA)
-   [Mike Fowler](https://www.swansea.ac.uk/staff/m.s.fowler/) (Swansea University, UK)
-   [Owen L. Petchey](https://www.ieu.uzh.ch/en/staff/member/petchey_owen.html) (University of Zurich, Switzerland)
-   [Samuel R.P-J. Ross](https://samuelrpjross.com/) (Okinawa Institute of Science and Technology Graduate University, Japan)
-   [Takehiro Sasaki](http://www.sasa-lab.ynu.ac.jp/pukiwiki-151/index.php) (Yokohama National University, Japan)
-   [Hannah J. White](https://aru.ac.uk/people/hannah-white) (Anglia Ruskin University, UK)
