---
title: "How to host a seminar"
description: "Guidelines on how to host a virtual seminar in the RDN seminar series"
author: "Admin"
date: "2025-03-20"
draft: false
---

\

It's great when members volunteer to host a seminar. If you're interested, please reach out to Sam or Owen. We can help you with the technical side of things, and we can also help you with the promotion of the seminar. Here are rough guidelines on what you'd need to do.

Seminars take place monthly on the last Wednesday of the month. The time is can be decided with the speaker, to accommodate different time zones.

1.  Who do you think will be an interesting speaker for the response diversity network? They don't have to be a member of the network, but they should be working on a topic that is relevant to the network. This could be a researcher, a practitioner, or someone from the policy world. They don't have to work directly on response diversity.

2.  Once you have an idea of a speaker in mind, check in with Owen and Sam. They can help find available date, and give some feedback on suitability.

3.  Reach out to the speaker to see if they are interested. If they are, you can work with them to find a date that works for both of you.

4.  Assemble and send to Owen or Sam the following information:

    -   Speaker name
    -   Speaker affiliation
    -   Speaker email
    -   Speaker website (if available)
    -   Title of the talk
    -   Abstract of the talk
    -   Speaker bio
    -   Speaker photo
    -   Date and time of the seminar
    -   Zoom link for the seminar (the seminar should be recorded)
    -   Any other relevant information

5.  Owen or Sam will create a web page for the seminar that can be used for advertising and providing information to attendees.

6.  Owen or Sam will email the network members with the details of the seminar.

7.  You should also promote the seminar on your own social media channels, and any other relevant channels.

8.  On the day of the seminar, you run the zoom session, you introduce the speaker, and moderate the Q&A session. You should also record the seminar.

9.  After the seminar, you should send the recording to Owen or Sam, who will upload it to the RDN YouTube channel.
