---
title: "Three opportunities to help policy- and decision-makers"
author: "Owen Petchey"
date: "2023-10-31"
draft: false
categories: ['Resource']
---

One of our aims is to provide advice about the importance and relevance of response diversity.

A few weeks ago I attended an online discussion, organised by [Globe-EU](https://www.globe-eu.org/) where Thomas Elmqvist talked about what response diversity is and why it is important. The discussion was titled: *Don’t put all your eggs in one basket - response diversity as a crisis management sustainability strategy.* An outline should soon be on the [Globe-EU website](https://www.globe-eu.org/).

I then chatted with Céline Tschirhart who is a Scientific Policy Officer working in the [Scientific Advice Mechanism](https://scientificadvice.eu/) (SAM) to the European Union. The SAM is an important way in which scientific advice can be provided to the European Union.

Here are three opportunities for you to help:

-   I would be very grateful if those of you that are active in such realms of providing advice to policy makers, in the EU or elsewhere, would please drop me a line if you're interested in helping us activate the RDN more in that direction. (We might then collate information and provide it to all RDN members.)

-   There will be a meeting in Brussels on 24th November 2023, Thomas is planned to be the main speaker, and participants be diverse and include policy makers and scientists. It will concern the importance of response diversity in the context of strategic crisis management. Please let me know if you're interested in attending in person or online.

-   The SAM works through the national academies of science, so you could contact your respect national academy of science and make them aware of you, the network, the importance of response diversity, and your willingness to help. Please let me know if you do this, so we can stay well coordinated.

Many thanks and best wishes, Owen
